### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by dcbuild3r** [dcbuild3r/blockchain-development-guide#2]
For the initial release of the blockchain development guide I'll release the following sections:
- **Intro**
- **How to get started**
- **Skill-based specializations:**
  - Front end
  - Back end
  - Smart contracts
  - Fullstack

- **Getting a job**
- **Mastery**
- **Social**

Once I publish these I'll focus on the building on Starknet, security engineering, protocol development, and cryptography sections.

**Comment by 0xJepsen** [comment]
Do you need help with any of these? What can I do to contribute to the resource?

**Comment by 0xJepsen** [comment]
Ohh maybe a cryptographic primitives section?

**Comment by dcbuild3r** [comment]
Any math, computer science resources you want to add you can, plus the cryptography section is up for grabs. Whatever you prefer
